/// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_empty = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled2 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled2 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_left = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_right = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_shopping_cart = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_add = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_bullet = IconData(0xf0ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_alt = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_empty = IconData(0xf0e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_alt = IconData(0xf0f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_squared = IconData(0xf0fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half_alt = IconData(0xf123, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_squared = IconData(0xf14a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_squared_alt = IconData(0xf196, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xf1e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus = IconData(0xf234, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commenting = IconData(0xf27a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xf290, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xf291, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat = IconData(0xf2ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat_ghost = IconData(0xf2ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
